name: fitnest-ci
on:
  push:
    branches:
      - '**'

env:
  CONFIG_EMAIL: ${{ secrets.CONFIG_EMAIL }}
  CONFIG_PASSWORD: ${{ secrets.CONFIG_PASSWORD }}
  CONFIG_SMTP_HOST: ${{ secrets.CONFIG_SMTP_HOST }}
  CONFIG_SMTP_PORT: ${{ secrets.CONFIG_SMTP_PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          remote_branch: "main"

      - name: Debug config log
        run: |
          cat email_config.yaml
          pwd
          ls