name: fitnest-ci
on:
  push:
    branches:
      - '**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Init config
        run: |
          echo -e email: 12345 >> email_config.yaml
          echo -e password: 12345 >> email_config.yaml
          echo -e smtpHost: 12345 >> email_config.yaml
          echo -e smtpPort: 12345 >> email_config.yaml

      - name: Debug config log
        run: cat email_config.yaml

      - uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          remote_branch: "main"